// <auto-generated />
namespace AuthNow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_Idpropertytocampaigntable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Idpropertytocampaigntable));
        
        string IMigrationMetadata.Id
        {
            get { return "201802240842531_User_Id property to campaign table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
